Informasjonsforvaltning/concept-catalog

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/repository/ConceptRepository.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt
=> chore: add functionality for getBegrep

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/DeleteConcept.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt
=> chore: add delete functionality

pom.xml, src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/model/Endringslogelement.kt, src/main/kotlin/no/fdk/concept_catalog/security/EndpointPermissions.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/kotlin/no/fdk/concept_catalog/validation/BegrepValidator.kt, src/main/resources/specification/specification.yaml, src/test/kotlin/no/fdk/concept_catalog/contract/UpdateConcept.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt
=> chore: add update

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/test/kotlin/no/fdk/concept_catalog/contract/DeleteConcept.kt
=> fix: bad request when deleting published

src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/model/Definisjon.kt, src/main/kotlin/no/fdk/concept_catalog/model/Kildebeskrivelse.kt, src/main/kotlin/no/fdk/concept_catalog/model/Term.kt, src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt, src/main/kotlin/no/fdk/concept_catalog/validation/BegrepValidator.kt, src/test/kotlin/no/fdk/concept_catalog/contract/UpdateConcept.kt
=> fix: handle null values from db

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt
=> fix: create adds log element

docker-compose.yaml, pom.xml, src/main/kotlin/no/fdk/concept_catalog/configuration/RabbitMQConfigurer.kt, src/main/kotlin/no/fdk/concept_catalog/model/DataSource.kt, src/main/kotlin/no/fdk/concept_catalog/repository/ConceptRepository.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptPublisher.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/application.yml, src/test/kotlin/no/fdk/concept_catalog/service/Rabbit.kt
=> feat: publish new collection when first concept for publisher is saved

src/main/kotlin/no/fdk/concept_catalog/controller/SkosApNoController.kt, src/main/kotlin/no/fdk/concept_catalog/rdf/RDFUtils.kt, src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetSkosApNoCollection.kt
=> chore: support standard rdf serializations

src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/specification/specification.yaml
=> feat: version number field

.github/workflows/deploy-prod.yaml, pom.xml, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/UpdateConcept.kt
resolves #56 
Dette blir første breaking-change pga ny flyt, så deaktiverer prod-deploy til ny flyt er fungerende i staging
=> feat: bad request for patch of published concepts

src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/specification/specification.yaml
=> feat: add fields originaltBegrep og revisjonAv

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/specification/specification.yaml, src/test/kotlin/no/fdk/concept_catalog/contract/CreateRevision.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt, src/test/kotlin/no/fdk/concept_catalog/utils/jwk/JwtToken.kt
=> feat: create revision from published concept

src/main/kotlin/no/fdk/concept_catalog/repository/ConceptRepository.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/kotlin/no/fdk/concept_catalog/validation/BegrepValidator.kt, src/test/kotlin/no/fdk/concept_catalog/service/Validation.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt
=> feat: validate versjonsnr

src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/kotlin/no/fdk/concept_catalog/validation/BegrepValidator.kt, src/main/resources/specification/specification.yaml, src/test/kotlin/no/fdk/concept_catalog/service/Validation.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt
=> feat: SemVer object

src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetSkosApNoConcept.kt, src/test/kotlin/no/fdk/concept_catalog/service/LastPublished.kt, src/test/kotlin/no/fdk/concept_catalog/service/SkosApNo.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt, src/test/resources/all_collections.ttl, src/test/resources/collection_0.ttl, src/test/resources/concept.ttl
=> feat: rdf-serialization handles several published versions

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/specification/specification.yaml, src/test/kotlin/no/fdk/concept_catalog/contract/CreateRevision.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt
=> feat: add body to revision creation

src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptMappers.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/specification/specification.yaml, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt
=> feat: add erSistPublisert to concepts

src/main/kotlin/no/fdk/concept_catalog/model/Status.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/specification/specification.yaml, src/test/kotlin/no/fdk/concept_catalog/contract/GetConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt
=> feat: add new status

pom.xml, src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt, src/main/resources/application.yml
Fixes Informasjonsforvaltning/fdk-issue-tracker#451
=> chore: enable micrometer metrics and submit using statsd

src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetCollections.kt
=> fix: only count concepts with several versions once when setting collection size

src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt, src/test/resources/all_collections.ttl, src/test/resources/collection_1.ttl
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/563
=> fix: correctly produce RDF for definitions with several sources

pom.xml, src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt, src/test/resources/all_collections.ttl, src/test/resources/collection_0.ttl, src/test/resources/concept.ttl
Resolves https://github.com/informasjonsforvaltning/fdk-issue-tracker/issues/567
=> produce RDF for begrepsrelasjon

pom.xml, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt
javax endra navn til jakarta i 2018 :sweat_smile:
=> chore: update json-patch dependencies

pom.xml, src/test/resources/all_collections.ttl, src/test/resources/collection_0.ttl, src/test/resources/collection_1.ttl, src/test/resources/concept.ttl
resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/510
=> chore: update concept-builder

src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt, src/test/resources/all_collections.ttl, src/test/resources/collection_0.ttl, src/test/resources/collection_1.ttl, src/test/resources/concept.ttl
=> fix: use correct concept uri in rdf

src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt
resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/598
=> chore: replace deprecated security config

pom.xml, src/main/kotlin/no/fdk/concept_catalog/model/SearchOperation.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptSearchService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/resources/all_collections.ttl, src/test/resources/collection_0.ttl, src/test/resources/concept.ttl
=> feat: add tillatt, frarådet & merknad as searchable fields

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/model/Pagination.kt, src/main/kotlin/no/fdk/concept_catalog/model/SearchOperation.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt
=> feat: paginate search result

pom.xml, src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/repository/ConceptRepository.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptMappers.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/CreateRevision.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetCollections.kt, src/test/kotlin/no/fdk/concept_catalog/service/LastPublished.kt, src/test/kotlin/no/fdk/concept_catalog/service/Validation.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt
=> feat: only support one unpublished revision of concepts

pom.xml, src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetConceptRevisions.kt
=> feat: revisions endpoint

docker-compose.yaml, src/main/kotlin/no/fdk/concept_catalog/configuration/ApplicationProperties.kt, src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/model/HistoricPayload.kt, src/main/kotlin/no/fdk/concept_catalog/model/User.kt, src/main/kotlin/no/fdk/concept_catalog/security/EndpointPermissions.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptMappers.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/kotlin/no/fdk/concept_catalog/service/HistoryService.kt, src/main/resources/application.yml, src/test/kotlin/no/fdk/concept_catalog/contract/UpdateConcept.kt, src/test/kotlin/no/fdk/concept_catalog/service/LastPublished.kt, src/test/kotlin/no/fdk/concept_catalog/service/Rabbit.kt, src/test/kotlin/no/fdk/concept_catalog/service/Validation.kt, src/test/kotlin/no/fdk/concept_catalog/utils/ContractMock.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt
=> feat: send updates to history-service

src/main/kotlin/no/fdk/concept_catalog/service/ConceptSearchService.kt
=> fix: published filter also hits null values when false

src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/repository/ConceptRepository.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptMappers.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/CreateRevision.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt
=> feat: add currentRevision to DTO

src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/model/InterntFelt.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptMappers.kt, src/main/resources/specification/specification.yaml, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt
=> feat: add internal fields

src/main/kotlin/no/fdk/concept_catalog/repository/ConceptRepository.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetCollections.kt, src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt, src/test/kotlin/no/fdk/concept_catalog/utils/jwk/JwtToken.kt
Fixes https://github.com/Informasjonsforvaltning/concept-catalog/issues/218
=> fix: support multiple revisions for search

pom.xml, src/main/kotlin/no/fdk/concept_catalog/controller/ChangeRequestController.kt, src/main/kotlin/no/fdk/concept_catalog/model/ChangeRequest.kt, src/main/kotlin/no/fdk/concept_catalog/repository/ChangeRequestRepository.kt, src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/ChangeRequests.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt
=> feat: add change request status

src/main/kotlin/no/fdk/concept_catalog/controller/ChangeRequestController.kt, src/test/kotlin/no/fdk/concept_catalog/contract/ChangeRequests.kt
=> fix: able to create & patch change requests with read access

src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt, src/main/kotlin/no/fdk/concept_catalog/validation/BegrepValidator.kt, src/test/kotlin/no/fdk/concept_catalog/contract/ChangeRequests.kt
=> chore: validate ansvarligVirksomhet.id as organization number

src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/model/SearchOperation.kt, src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptMappers.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptSearchService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/contract/UpdateConcept.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestUtils.kt
resolves https://github.com/Informasjonsforvaltning/concept-catalog/issues/229
=> Filter by assignedUser

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptMappers.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/service/Rabbit.kt, src/test/kotlin/no/fdk/concept_catalog/utils/ContractMock.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt
=> user generated values are sent to history service during create

src/main/kotlin/no/fdk/concept_catalog/configuration/ApplicationProperties.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/application.yml
=> feat: save history in all environments

src/main/kotlin/no/fdk/concept_catalog/configuration/ApplicationProperties.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/application.yml
This reverts commit 642765134e659b8414ca3ad2dca1d140619a2236.
=> Revert "feat: save history in all environments"

src/main/kotlin/no/fdk/concept_catalog/configuration/ApplicationProperties.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/application.yml
This reverts commit 9ba6dd1ab21049a607615bae67409fb95a8361ba.
Har testa ok i demo og prod
=> Revert "Revert "feat: save history in all environments""

docker-compose.yaml, pom.xml, src/main/kotlin/no/fdk/concept_catalog/Application.kt, src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/elastic/ConceptSearchRepository.kt, src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/model/Endringslogelement.kt, src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptSearchService.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/application.yml, src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/service/LastPublished.kt, src/test/kotlin/no/fdk/concept_catalog/service/Rabbit.kt, src/test/kotlin/no/fdk/concept_catalog/service/Validation.kt, src/test/kotlin/no/fdk/concept_catalog/utils/ApiTestContext.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt
=> feat: ConceptSearchService uses elasticsearch

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/elastic/ElasticUpdater.kt, src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptSearchService.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/resources/elastic/mappings.json, src/main/resources/elastic/settings.json, src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt
=> add ngram analysis for search-fields

src/main/kotlin/no/fdk/concept_catalog/elastic/CurrentConceptRepository.kt, src/main/kotlin/no/fdk/concept_catalog/elastic/ElasticUpdater.kt, src/main/kotlin/no/fdk/concept_catalog/model/CurrentConcept.kt, src/main/kotlin/no/fdk/concept_catalog/model/Pagination.kt, src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptSearchService.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/service/LastPublished.kt, src/test/kotlin/no/fdk/concept_catalog/service/Rabbit.kt, src/test/kotlin/no/fdk/concept_catalog/service/Validation.kt
=> chore: add extra search index for current versions

src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/resources/application.yml
=> chore: add mongodb compound indices

src/main/kotlin/no/fdk/concept_catalog/model/SearchOperation.kt, src/main/kotlin/no/fdk/concept_catalog/model/SortField.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptSearchService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt
boost-tall er ren gjetting, men det kan vi vel skru litt på ved behov senere
=> feat: relevance as default sort, boost title hits and phrases

src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/ChangeRequests.kt
=> fix: createChangeRequest takes operations from body

src/main/kotlin/no/fdk/concept_catalog/Application.kt, src/main/kotlin/no/fdk/concept_catalog/service/JsonPatchUtils.kt
=> fix: log exceptions when applying json patch operations

src/main/kotlin/no/fdk/concept_catalog/Application.kt, src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/main/kotlin/no/fdk/concept_catalog/service/JsonPatchUtils.kt, src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
la til mer logging der det skjer oppdateringer i databasen og fjerna den rimelig unyttige debug-loggingen i SkosApNoService
=> chore: more error and debug logs

src/main/kotlin/no/fdk/concept_catalog/rdf/AUDIENCE_TYPE.kt, src/main/kotlin/no/fdk/concept_catalog/rdf/EUVOC.kt, src/main/kotlin/no/fdk/concept_catalog/rdf/RELATIONSHIP.kt, src/main/kotlin/no/fdk/concept_catalog/rdf/SKOSNO.kt, src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt, src/test/kotlin/no/fdk/concept_catalog/service/SkosApNo.kt, src/test/resources/all_collections.ttl, src/test/resources/collection_0.ttl, src/test/resources/collection_1.ttl, src/test/resources/concept.ttl
closes https://github.com/Informasjonsforvaltning/concept-catalog/issues/343
=> chore: update defintion according to skos v2

src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt, src/test/resources/all_collections.ttl, src/test/resources/collection_0.ttl, src/test/resources/collection_1.ttl, src/test/resources/concept.ttl
closes [#344](https://github.com/Informasjonsforvaltning/concept-catalog/issues/344)
=> chore: update labels according to skos v2

src/main/kotlin/no/fdk/concept_catalog/rdf/EUVOC.kt, src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt, src/test/resources/all_collections.ttl, src/test/resources/collection_0.ttl, src/test/resources/collection_1.ttl
closes [#350](https://github.com/Informasjonsforvaltning/concept-catalog/issues/350)
closes [#348](https://github.com/Informasjonsforvaltning/concept-catalog/issues/348)
=> chore: update concept collection according to skos v2

.github/workflows/deploy-prod&demo.yaml, .github/workflows/deploy-staging.yaml, deploy/base/concept-catalog-deployment.yaml, deploy/base/concept-catalog-service.yaml, deploy/base/kustomization.yaml, deploy/demo/env.yaml, deploy/demo/kustomization.yaml, deploy/prod/env.yaml, deploy/prod/kustomization.yaml, deploy/staging/env.yaml, deploy/staging/kustomization.yaml
=> feat: add deploy with kustomize

src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt
This reverts commit f22ee4ea3e879296959adef6d8ea4ab5970ea946.
=> Revert "feat: add csp header"

pom.xml, src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt, src/test/kotlin/no/fdk/concept_catalog/service/SkosApNo.kt, src/test/resources/all_collections.ttl, src/test/resources/collection_1.ttl
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/993
=> fix: correct RDF serialization of sources

deploy/demo/env.yaml, deploy/prod/env.yaml, deploy/staging/env.yaml, src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt, src/main/resources/application.yml
resolve https://github.com/Informasjonsforvaltning/fdk-team-private/issues/115
=> chore: update cors config

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/rdf/RDFUtils.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/ContractTestsBase.kt, src/test/kotlin/no/fdk/concept_catalog/contract/ChangeRequests.kt, src/test/kotlin/no/fdk/concept_catalog/contract/CreateConcept.kt, src/test/kotlin/no/fdk/concept_catalog/contract/CreateConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/contract/CreateRevision.kt, src/test/kotlin/no/fdk/concept_catalog/contract/DeleteConcept.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetCollections.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetConcept.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetConceptRevisions.kt, src/test/kotlin/no/fdk/concept_catalog/contract/GetConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/contract/PublishConcept.kt, src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/contract/SuggestConcepts.kt, src/test/kotlin/no/fdk/concept_catalog/contract/UpdateConcept.kt
Ein mini pr med sjølve kontrakten. Pluss noko refaktorering av testoppsett.
=> Contract for import rdf + refactoring

src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/controller/SkosApNoController.kt, src/main/kotlin/no/fdk/concept_catalog/model/Begrep.kt, src/main/kotlin/no/fdk/concept_catalog/rdf/RDFUtils.kt, src/main/kotlin/no/fdk/concept_catalog/rdf/SkosApNoImport.kt, src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/rdf/SkosApNoImportTests.kt, src/test/resources/concept.ttl, src/test/resources/import_concept.ttl
=> Rdf mapping

src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/DeleteConcept.kt
resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1050
=> fix: update search with latest version on delete

src/main/kotlin/no/fdk/concept_catalog/controller/ImportController.kt, src/main/kotlin/no/fdk/concept_catalog/model/ConceptExtraction.kt, src/main/kotlin/no/fdk/concept_catalog/model/ExtractResult.kt, src/main/kotlin/no/fdk/concept_catalog/model/ExtractionRecord.kt, src/main/kotlin/no/fdk/concept_catalog/model/ImportResult.kt, src/main/kotlin/no/fdk/concept_catalog/model/Issue.kt, src/main/kotlin/no/fdk/concept_catalog/rdf/RdfImport.kt, src/main/kotlin/no/fdk/concept_catalog/repository/ImportResultRepository.kt, src/main/kotlin/no/fdk/concept_catalog/service/ImportService.kt, src/test/kotlin/no/fdk/concept_catalog/ContractTestsBase.kt, src/test/kotlin/no/fdk/concept_catalog/contract/ImportControllerTests.kt, src/test/kotlin/no/fdk/concept_catalog/rdf/RdfImportTests.kt
Kan nok optimaliserast noko med bulk oppdateringer (eks. history-service) og async, men det får bli i neste iterasjon. Dette er meir enn godt nok, for det me har av testressurser per i dag (dvs. intern testing).
=> Skosapno rdf import

deploy/base/concept-catalog-deployment.yaml, deploy/demo/env.yaml, deploy/prod/env.yaml, deploy/staging/env.yaml, src/main/kotlin/no/fdk/concept_catalog/elastic/ElasticProperties.kt, src/main/kotlin/no/fdk/concept_catalog/elastic/ElasticsearchConfig.kt, src/main/resources/application.yml, src/test/kotlin/no/fdk/concept_catalog/ContractTestsBase.kt, src/test/kotlin/no/fdk/concept_catalog/ElasticTestConfig.kt
resolve https://github.com/Informasjonsforvaltning/fdk-team-private/issues/143
=> chore: change elastic host

.github/workflows/codeql.yaml, .github/workflows/deploy-prod&demo.yaml, .github/workflows/deploy-staging.yaml, pom.xml, src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt, src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/DeleteConcept.kt, src/test/kotlin/no/fdk/concept_catalog/utils/TestData.kt
fixes https://github.com/Informasjonsforvaltning/concept-catalog/issues/435
=> feat: delete change request if related concept is deleted

src/main/kotlin/no/fdk/concept_catalog/service/ConceptService.kt, src/test/kotlin/no/fdk/concept_catalog/contract/PublishConcept.kt
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1156
=> fix: update elastic on publish

src/main/kotlin/no/fdk/concept_catalog/rdf/RDFImport.kt, src/test/kotlin/no/fdk/concept_catalog/rdf/RDFImportTests.kt
=> Fix/mapping to relationship with source #468
